export const bibliotheques = [
  { id: "amenagement", titre: "Aménagement", autreTitre: "Bibliothèque d'aménagement" },
  { id: "parc", titre: "Parc", autreTitre: "Bibliothèque du Parc" },
  { id: "conservation", titre: "Centre de conservation Lionel-Groulx", autreTitre: "Centre de conservation Lionel-Groulx" },
  { id: "lrcs", titre: "Livres rares et collections spéciales", autreTitre: "Bibliothèque des livres rares et collections spéciales" },
  { id: "droit", titre: "Droit", autreTitre: "Bibliothèque de droit" },
  { id: "tgd", titre: "Thérèse-Gouin-Décarie", autreTitre: "Bibliothèque Thérèse-Gouin-Décarie" },
  { id: "jardin-botanique", titre: "Point de service : À venir - Jardin Botanique, Brossard, Médecine", autreTitre: "Point de service : À venir - Jardin Botanique, Brossard, Médecine" },
  { id: "kinesiologie", titre: "Kinésiologie", autreTitre: "Bibliothèque de kinésiologie" },
  { id: "laval", titre: "Campus de Laval", autreTitre: "Bibliothèque du campus de l'UdeM à Laval" },
  { id: "marcel-laurin", titre: "Centre de conservation Marcel-Laurin", autreTitre: "Centre de conservation 101, boul. Marcel-Laurin" },
  { id: "math-info", titre: "Mathématiques et informatique", autreTitre: "Bibliothèque de mathématiques et informatique" },
  { id: "musique", titre: "Musique", autreTitre: "Bibliothèque de musique" },
  { id: "medecine-veterinaire", titre: "Médecine vétérinaire", autreTitre: "Bibliothèque de médecine vétérinaire" },
  { id: "marguerite-d-youville", titre: "Marguerite-d'Youville", autreTitre: "Bibliothèque Marguerite-d'Youville" },
  { id: "sante", titre: "Santé", autreTitre: "Bibliothèque de la santé" },
  { id: "Hubert-reeves", titre: "Hubert-Reeves", autreTitre: "Bibliothèque Hubert-Reeves" },
  { id: "lsh", titre: "Lettres et sciences humaines", autreTitre: "Bibliothèque des lettres et sciences humaines" },
]
